# Training Configuration
TRAINING_SCRIPT: "train.py"

# Experiment Results
RESULT_FILE: "./files/analysis/loss.csv"
RESULT_FILE_TEST: "./files/analysis/benchmark.csv"

# Debug Configuration
DEBUG_FOLDER: "./files/debug"

# Code Pool Directory (InvisMark)
CODE_POOL: "./pool/invismark"

# SOURCE_FILE is automatically constructed as: {CODE_POOL}/{CODE_POOL_FOLDERNAME}_base.py

# Model Architecture Directory
ARCHITECTURE: "invismark"

# Retry and Debug Limits
MAX_DEBUG_ATTEMPT: 5
MAX_RETRY_ATTEMPTS: 20

# Service URLs
RAG: "http://127.0.0.1:13124"
DATABASE: "http://localhost:8001"
