# Azure OpenAI API Configuration
AZURE_ENDPOINT: "https://some_endpoint.openai.azure.com/"
AZURE_DEPLOYMENT: "gpt-5-2"

# Model-Specific Deployments
AZURE_DEPLOYMENT_MODEL_JUDGER: "gpt-5-2"
AZURE_DEPLOYMENT_MODEL_ANALYZER: "gpt-5-2"
AZURE_DEPLOYMENT_MODEL_CHECKER: "gpt-5-2"
AZURE_DEPLOYMENT_MODEL_EVOLVER: "gpt-5-2"
AZURE_DEPLOYMENT_MODEL_PLANNER: "gpt-5-2"
AZURE_DEPLOYMENT_MODEL_SUMMARIZER: "gpt-5-2"
AZURE_DEPLOYMENT_MODEL_DEBUGGER: "gpt-5-2"
AZURE_DEPLOYMENT_MODEL_TRAINER: "gpt-5-2"
AZURE_DEPLOYMENT_MODEL_MOTIVATION_CHECKER: "gpt-5-2"
AZURE_DEPLOYMENT_RAG_GENERATION: "gpt-5-2"

# API Configuration
API_VERSION: "2025-01-01-preview"
API_KEY: "xxxxxxxxxxx"
